POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsenUxIiwiaWQiOiI2MjJiNTRmNGVhODZmNDIyOGNlNjcyNTciLCJpYXQiOjE2NDcwMDcwMDl9.bTyeUZmUNamOjB92BzrIxrqw33PAVg7HHGh699iqDGc

{
  "title": "commment test",
  "author": "test Hel",
  "url": "http://testest.com",
  "likes": "9000"
}

###

GET http://localhost:3003/api/blogs/625c265c9beecd71a40642cf
Content-Type: application/json


###
post http://localhost:3003/api/users
Content-Type: application/json

  {
      "username": "alzu1",
      "name": "alzbeta",
      "password": "alzu1"
  }

###
delete http://localhost:3003/api/blogs/622b77d77257ffd2c3103941
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsenUxIiwiaWQiOiI2MjJiNTRmNGVhODZmNDIyOGNlNjcyNTciLCJpYXQiOjE2NDczMzEyOTJ9.CU2KY0CfjrS8aayAIeGEQPRzzTpo2uk-ThKlovCWu7o

###

post http://localhost:3003/api/login
Content-Type: application/json

  {
      "username": "alzu1",
      "password": "alzu1"
  }

###
POST   http://localhost:3003/api/blogs/625d3d6feda462a6ad303e87/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsenUxIiwiaWQiOiI2MjJiNTRmNGVhODZmNDIyOGNlNjcyNTciLCJpYXQiOjE2NDczMzEyOTJ9.CU2KY0CfjrS8aayAIeGEQPRzzTpo2uk-ThKlovCWu7o

{
  "text": "second commment is here"
}