POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "dateOfBirth":	"1944-07-22",   
    "name":	"Zdena Studenkova",
    "gender": "female",
    "ssn": "212121-2121",
    "occupation": "chef"
}

###
GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e157777
Content-Type: application/json